### ISSUE TITLE
Course Schema

### ISSUE THREAD

**Issue by huseinr2493** [uwstout-cs458-s22/advisor001-api#29]
As a `developer`, I would like to design and create a table for courses so that I can persist Course models.

- The schema in `/services/database` exists and responds properly when queried
- The schema responses with the appropriate information that was added
- The schema is able to be understood by the group, with each member able to explain why each column is necessary.

**Comment by joshua-elmer** [comment]
Here is what I commented on the "Term Schema" task

My best start is that a "Term" would need to have basic identifying information, like a year and season (Fall 2021/Spring 2022/etc.) and then a primary key ID field that courses reference via a foreign key to say what term they are available in.

So for example a term might be written as essentially:

{'termId': int, 'year': int, 'season': string}

The main problem I see in this form is that since each term would have to have a unique ID, in order to show a course as available in multiple terms, it would need to have multiple foreign keys to the terms, or a new copy of the course for each term it is offered in.

But I would follow what Professor Schmidt said about how the person planning a term would want them to work over what I have here.
